name: gamename
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  flame: ^1.28.1
  flame_audio: ^2.11.5
  device_preview: ^1.2.0
  flutter_draggable_gridview: ^0.0.13
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  url_launcher_windows: 3.1.4
  intl: ^0.19.0
  provider: ^6.1.4
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.0.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icons/iOS/1024x1024.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen_bgimg.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
