name: checkgrid
description: "An amazing mobile game."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  # Necessary for the app
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.4 # Provider
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0 # Fonts
  flutter_draggable_gridview: ^0.0.13 # Game grid
  flutter_local_notifications: ^19.1.0 # Notifications
  flutter_native_splash: ^2.4.6 # Splashscreen
  flutter_spinkit: ^5.2.0 # Loading animation
  google_mobile_ads: ^6.0.0 # Ads
  google_fonts: ^6.2.1 # Font
  image_picker: ^1.1.2 # Pick images from phone
  url_launcher: ^6.3.1 # Launch url's
  url_launcher_windows: ^3.1.4 # Launch url's
  go_router: ^16.0.0 # Navigation
  flutter_timezone: ^4.1.0 # Correct timezones
  timezone: ^0.10.1 # Correct timezones
  lottie: ^3.3.1 # Lottie animations (custom)
  flame: ^1.29.0 # Game Engine
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  vibration: ^3.1.3 # Vibrations
  audioplayers: ^6.1.0 # Sound effects
  # in_app_purchase: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icons/iOS/1024x1024.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen_bgimg.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    # Audio assets
    - assets/audio/
    - assets/audio/place_piece/
    - assets/audio/pick_up/
    - assets/audio/menu/

    # Image assets
    - assets/images/
    - assets/images/animations/
    - assets/images/difficulties/
    - assets/images/dialog_images/
    - assets/images/dialog_images/settings_icon.png
    - assets/images/dialog_images/difficulty_icon.png
    # Add new skins here:
    - assets/images/pieces/white/
    - assets/images/pieces/black/
    - assets/images/pieces/blue/