name: gamename
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  flame: ^1.28.1
  flame_audio: ^2.11.5
  device_preview: ^1.2.0
  flutter_draggable_gridview: ^0.0.13
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  url_launcher_windows: 3.1.4
  intl: ^0.19.0
  provider: ^6.1.4
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.0.0
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
